# Generated by Django 5.2.7 on 2025-12-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitallead',
            name='lead_source',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Lead', 'Lead')], default='Customer', max_length=20),
        ),
    ]
