# Generated by Django 5.2.7 on 2025-12-06 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('Travel', 'Travel'), ('Food', 'Food'), ('Office Stationary', 'Office Stationary'), ('Fuel', 'Fuel'), ('Misc', 'Misc'), ('Online E-commerce', 'Online E-commerce'), ('Accommodation', 'Accommodation')], max_length=100)),
                ('remark', models.TextField(blank=True, null=True)),
                ('bill_image', models.ImageField(blank=True, null=True, upload_to='staff_bills/')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_expenses', to='leads.staff')),
            ],
        ),
    ]
